lane :pods do
	cocoapods(podfile: "Example/", repo_update: true)
end

lane :tests do
	pods
	scan(workspace: "Example/TVDB.xcworkspace",
		scheme: "TVDBTests",
		clean: false,
		code_coverage: true,
		output_directory: "./reports/")
end

desc "Run all tests and linters"
lane :lint do
	tests
	pod_lib_lint(allow_warnings: true, verbose: false)
	slather(cobertura_xml: true,
			travis: true,
			scheme: "TVDBTests",
			output_directory: "./reports",
			verbose: true,
			proj: "Example/TVDB.xcodeproj",
			workspace: "Example/TVDB.xcworkspace")
    sh("cd .. && lizard ./Example -l swift --xml > ./reports/lizard-report.xml")
    swiftlint(output_file: "./reports/swiftlint.txt", ignore_exit_status: true)
end

desc "Run all tests and linters then upload metrics to sonar"
lane :upload_sonar do
	lint
	sonar(sonar_login: ENV["SONAR_LOGIN"])
end